### ISSUE TITLE
SE (since its client) is supposed to make request to the test tool

### ISSUE THREAD

**Issue by prashantbhure** [GlobalPlatform/SE_Abstract_Communication_Layer_Over_TCP_IP#1]
A server host runs one or more server programs which share their resources and provides services to clients. 
A client does not share any of its resources, but requests a server's content or service function. 
Clients therefore initiate communication sessions with servers which await incoming requests. 
Hence in our view, the entity which is integrated with TestTool should be client and the entity which deals with the SE (Secure Element)is the server.
Hence the role of client and server should be reversed.
As per the current design, card/SE (since its client) is supposed to make request to the test tool which should not be the case.
Also with the current design, we will be having 2 clients one for contact interface and another for contactless interface.

With reversed roles, test tool (client) can connect to server on the same port by having interface information in header.

**Comment by ovnh** [comment]
NXP will look internally and provide feedback.

**Comment by ovnh** [comment]
NXP accepts the current implementation.
