### ISSUE TITLE
Usage of JSON data format for data transmission

### ISSUE THREAD

**Issue by prashantbhure** [GlobalPlatform/SE_Abstract_Communication_Layer_Over_TCP_IP#2]
Using JSON data format for data transmission over TCP/IP may create additional overhead and may have a negative impact on the test execution speed finally.
It could be proprietary exchange data format.

**Comment by ovnh** [comment]
The implementation tried to still open for improvement (reason to use JSON).
However, the performance and loading were important and take account.
The preliminary test performed not highlighted "significant" performance decreasing and the loading test was perform during more than 24 hours (without issues).
