### ISSUE TITLE
Licenses for libraries to be used by client

### ISSUE THREAD

**Issue by prashantbhure** [GlobalPlatform/SE_Abstract_Communication_Layer_Over_TCP_IP#3]
Usage of below open source libraries on client side:
Library Nlohmann JSON (https://github.com/nlohmann/json) - MIT licence type
Library Plog (https://github.com/SergiusTheBest/plog)    - Mozilla Public License 

-Do we need to publish client on github?
Based on the library type, we will have to check internally if client using the provided libraries can be published.

**Comment by ovnh** [comment]
The topic should be checked but looking for laywer...

**Comment by ovnh** [comment]
NLohmann does not have limitation. Only mention not liability and not warranty of the code (allow to sell the software)
Plog is the tool is delivered under executable form need to mention to the recipient that Plog is used and allow the recipient to have access to the source code of Plog (not all the code). As it is an open project, this should not lead to an issue (as the reusable part is in this open project).
