### ISSUE TITLE
MSG_WAITALL

### ISSUE THREAD

**Issue by blacoste** [GlobalPlatform/SE_Abstract_Communication_Layer_Over_TCP_IP#6]
Client build fails if preprocessor MSG_WAITALL variable is not define.

Proposition: 
- should use an internal default practical value for MSG_WAITALL. 
- overload might still be supported using this variable.

**Comment by ovnh** [comment]
This has should be solved in the Master Branch.

It seems linked with the IDE. Eclipse didn't have the issue where Visual Studio had it.

We changed the release on windows (and it works now).
